### ISSUE TITLE
Adjust fixed width

### ISSUE THREAD

**Issue by knsh14** [playcanvas/fonts#10]
Most of game's UI has fixed text width. (ranking, high score ...)
changing text scale to fit width.
if user set max line, then insert line break until max line to keep text size.

can I try it?

**Comment by vkalpias** [comment]
I'm not sure what you would like to try - Have you checked out the new Element component that allows you to render beautiful text? https://developer.playcanvas.com/en/user-manual/user-interface/text-elements/
