### ISSUE TITLE
JS warning: RENDER WARNING: Render count or primcount is 0.

### ISSUE THREAD

**Issue by marionieto** [playcanvas/fonts#5]
When a font_renderer hasn't set a text, it throws a warning message into JS console.
This warning is throw in each update.

The full warning:
![image](https://cloud.githubusercontent.com/assets/2238679/17304771/9ee2b126-57fd-11e6-86c6-0ecb243b24bb.png)
[.CommandBufferContext.Offscreen-MainThread-0x7ffac37f61d0]RENDER WARNING: Render count or primcount is 0.

**Comment by willeastcott** [comment]
Closing since this repo is now retired. Please use the element component instead.
