### ISSUE TITLE
can you add some sample font files or at least one example?

### ISSUE THREAD

**Issue by liesislukas** [playcanvas/fonts#7]
I believe you already have some generated, so it would be great to have it ready to use for all of us

**Comment by willeastcott** [comment]
Sure! :smile: 

Fixed in 24a368b891119f78fe998056ee9037188bf5abda

![image](https://cloud.githubusercontent.com/assets/697563/19033527/c32748c8-8956-11e6-8448-318dc309a1f6.png)

**Comment by liesislukas** [comment]
thanks :)
